/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.ControllerActuator;
import controllers.ControllerGps;
import controllers.ControllerSensor;
import controllers.ControllerVehicule;
import java.util.UUID;
import javax.swing.JOptionPane;
import models.*;
import utils.Fonts;
import utils.Colors;

/**
 *
 * @author Usuario
 */
public class CreateVehicle extends javax.swing.JFrame {

    /**
     * Creates new form CreateDeviceGPS
     */
    public CreateVehicle() {
        initComponents();

        for (var iot : ControllerActuator.listaActuador.listar()) {
            this.customChoose4.addItem(iot.getNombre() + " - " + iot.getIp());
        }

        for (var iot : ControllerSensor.listaSensor.listar()) {
            this.customChoose1.addItem(iot.getNombre() + " - " + iot.getIp());
        }

        for (var iot : ControllerGps.listaGPS.listar()) {
            this.customChoose2.addItem(iot.getNombre() + " - " + iot.getIp());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customChoose1 = new components.CustomChoose();
        customButton1 = new components.CustomButton();
        customButton2 = new components.CustomButton();
        customButton3 = new components.CustomButton();
        customButton4 = new components.CustomButton();
        jLabel5 = new javax.swing.JLabel();
        customChoose2 = new components.CustomChoose();
        jLabel6 = new javax.swing.JLabel();
        customChoose3 = new components.CustomChoose();
        customChoose4 = new components.CustomChoose();
        jLabel7 = new javax.swing.JLabel();
        customTextField1 = new components.CustomTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Colors.white);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(Colors.white);
        jPanel1.setForeground(Colors.white);
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(Fonts.title);
        jLabel1.setForeground(Colors.mediumBlue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Vehiculo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, -1));

        jLabel4.setFont(Fonts.normal);
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        customChoose1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sensor 1" }));
        jPanel1.add(customChoose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 680, -1));

        customButton1.setText("Eliminar");
        customButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customButton1MouseClicked(evt);
            }
        });
        jPanel1.add(customButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 130, 40));

        customButton2.setText("Registrar");
        customButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customButton2MouseClicked(evt);
            }
        });
        jPanel1.add(customButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 130, 40));

        customButton3.setText("Editar");
        customButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customButton3MouseClicked(evt);
            }
        });
        jPanel1.add(customButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 130, 40));

        customButton4.setText("Buscar");
        customButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customButton4MouseClicked(evt);
            }
        });
        jPanel1.add(customButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 130, 40));

        jLabel5.setFont(Fonts.normal);
        jLabel5.setText("GPS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        customChoose2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GPS 1" }));
        jPanel1.add(customChoose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 680, -1));

        jLabel6.setFont(Fonts.normal);
        jLabel6.setText("Modelo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        customChoose3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Honda" }));
        jPanel1.add(customChoose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 680, -1));

        customChoose4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Actuador 1" }));
        customChoose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customChoose4ActionPerformed(evt);
            }
        });
        jPanel1.add(customChoose4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 680, -1));

        jLabel7.setFont(Fonts.normal);
        jLabel7.setText("Actuador temperatura");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        customTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(customTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 680, -1));

        jLabel8.setFont(Fonts.normal);
        jLabel8.setText("Sensor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customChoose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customChoose4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customChoose4ActionPerformed

    private void customButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customButton2MouseClicked
        String actuatorIP = this.customChoose4.getSelectedItem().toString().split(" - ")[1];
        var actuator = (ActuadorTemperatura) ControllerActuator.search(actuatorIP);

        String sensorIP = this.customChoose1.getSelectedItem().toString().split(" - ")[1];
        var sensor = (SensorTemperatura) ControllerSensor.search(sensorIP);

        String gpsIP = this.customChoose2.getSelectedItem().toString().split(" - ")[1];
        var GPS = (GPS) ControllerGps.search(gpsIP);

        VehiculoRefrigerado vehiculoRefrigerado = new VehiculoRefrigerado(
                UUID.randomUUID().toString(),
                this.customChoose3.getSelectedItem().toString(),
                sensor,
                GPS,
                actuator
        );

        ControllerVehicule.add(vehiculoRefrigerado);
        JOptionPane.showMessageDialog(this, "Se ha añadido correctamente");
        ControllerVehicule.list();
        clear();
    }//GEN-LAST:event_customButton2MouseClicked

    private void customButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customButton4MouseClicked
        var vehicle = ControllerVehicule.search(this.customTextField1.getText());

        this.customChoose1.setSelectedItem(vehicle.getSensorTemperatura().getNombre() + " - " + vehicle.getSensorTemperatura().getIp());
        this.customChoose2.setSelectedItem(vehicle.getGps().getNombre() + " - " + vehicle.getSensorTemperatura().getIp());
        this.customChoose3.setSelectedItem(vehicle.getModelo());
        this.customChoose4.setSelectedItem(vehicle.getActuadorTemperatura().getNombre() + " - " + vehicle.getSensorTemperatura().getIp());

    }//GEN-LAST:event_customButton4MouseClicked

    private void customButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customButton3MouseClicked

        String actuatorIP = this.customChoose4.getSelectedItem().toString().split(" - ")[1];
        var actuator = (ActuadorTemperatura) ControllerActuator.search(actuatorIP);

        String sensorIP = this.customChoose1.getSelectedItem().toString().split(" - ")[1];
        var sensor = (SensorTemperatura) ControllerSensor.search(sensorIP);

        String gpsIP = this.customChoose2.getSelectedItem().toString().split(" - ")[1];
        var GPS = (GPS) ControllerGps.search(gpsIP);

        VehiculoRefrigerado vehiculoRefrigerado = new VehiculoRefrigerado(
                UUID.randomUUID().toString(),
                this.customChoose3.getSelectedItem().toString(),
                sensor,
                GPS,
                actuator
        );
        
        ControllerVehicule.edit(this.customTextField1.getText(), vehiculoRefrigerado);
        JOptionPane.showMessageDialog(this, "Se ha editado correctamente");
        clear();
    }//GEN-LAST:event_customButton3MouseClicked

    private void customButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customButton1MouseClicked

        ControllerVehicule.delete();
        JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente");
        clear();
    }//GEN-LAST:event_customButton1MouseClicked

    private void customTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateVehicle().setVisible(true);
            }
        });
    }

    private void clear() {
        customChoose1.setSelectedIndex(0);
        customChoose2.setSelectedIndex(0);
        customChoose3.setSelectedIndex(0);
        customChoose4.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private components.CustomButton customButton1;
    private components.CustomButton customButton2;
    private components.CustomButton customButton3;
    private components.CustomButton customButton4;
    private components.CustomChoose customChoose1;
    private components.CustomChoose customChoose2;
    private components.CustomChoose customChoose3;
    private components.CustomChoose customChoose4;
    private components.CustomTextField customTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
