/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.ControllerLightbulb;
import java.awt.Color;
import java.awt.Cursor;
import java.util.UUID;
import javax.swing.JOptionPane;
import models.FocoInteligente;
import utils.Fonts;
import utils.Colors;

/**
 *
 * @author Usuario
 */
public class CreateLightbulb extends javax.swing.JFrame {
    
    private static final String IPV4_PATTERN_ALLOW_LEADING_ZERO =
            "^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
            "([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
            "([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
            "([01]?\\d\\d?|2[0-4]\\d|25[0-5])$";

    /**
     * Creates new form CreateDeviceGPS
     */
    public CreateLightbulb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customTextField2 = new components.CustomTextField();
        customTextField4 = new components.CustomTextField();
        customChoose1 = new components.CustomChoose();
        eliminarFocosBtn = new components.CustomButton();
        registrarFocosBtn = new components.CustomButton();
        editarFocosBtn = new components.CustomButton();
        buscarFocosBtn = new components.CustomButton();
        customTextField5 = new components.CustomTextField();
        jLabel7 = new javax.swing.JLabel();
        customTextField6 = new components.CustomTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Colors.white);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(Colors.white);
        jPanel1.setForeground(Colors.white);
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(Fonts.title);
        jLabel1.setForeground(Colors.mediumBlue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Focos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, -1));

        jLabel2.setFont(Fonts.normal);
        jLabel2.setText("IP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(Fonts.normal);
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setFont(Fonts.normal);
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(Fonts.normal);
        jLabel6.setText("Intensidad maxima");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        customTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField2ActionPerformed(evt);
            }
        });
        customTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(customTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 680, -1));

        customTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(customTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 680, -1));

        customChoose1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zigbee", " " }));
        jPanel1.add(customChoose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 680, -1));

        eliminarFocosBtn.setText("Eliminar");
        eliminarFocosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarFocosBtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarFocosBtnMousePressed(evt);
            }
        });
        jPanel1.add(eliminarFocosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 130, 40));
        eliminarFocosBtn.setCursor(new Cursor(HAND_CURSOR));

        registrarFocosBtn.setText("Registrar");
        registrarFocosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarFocosBtnMouseClicked(evt);
            }
        });
        registrarFocosBtn.setCursor(new Cursor(HAND_CURSOR));
        jPanel1.add(registrarFocosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 130, 40));

        editarFocosBtn.setText("Editar");
        editarFocosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarFocosBtnMouseClicked(evt);
            }
        });
        jPanel1.add(editarFocosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 130, 40));
        editarFocosBtn.setCursor(new Cursor(HAND_CURSOR));

        buscarFocosBtn.setText("Buscar");
        buscarFocosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarFocosBtnMouseClicked(evt);
            }
        });
        jPanel1.add(buscarFocosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 130, 40));
        buscarFocosBtn.setCursor(new Cursor(HAND_CURSOR));

        customTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(customTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 680, -1));

        jLabel7.setFont(Fonts.normal);
        jLabel7.setText("Potencia de consumo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        customTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(customTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 680, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField4ActionPerformed

    private void customTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField5ActionPerformed

    private void customTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField6ActionPerformed

    private void registrarFocosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarFocosBtnMouseClicked
        try{
            
            FocoInteligente focoInteligente = new FocoInteligente(
                UUID.randomUUID().toString(),
                this.customTextField2.getText(),
                "apagado",
                this.customTextField5.getText(),
                this.customChoose1.getSelectedItem().toString(),
                "1.2.2.3",
                Integer.parseInt(this.customTextField4.getText()),
                Integer.parseInt(this.customTextField6.getText()),
                new Color(10, 10, 10),
                10,
                10
        );
            ControllerLightbulb.add(focoInteligente);
            limpiar();
            JOptionPane.showMessageDialog(this, "Se ha agregado correctamente");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrio un error, intenta nuevamente");
        }
    }//GEN-LAST:event_registrarFocosBtnMouseClicked

    private void customTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_customTextField2ActionPerformed

    private void editarFocosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarFocosBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editarFocosBtnMouseClicked

    private void buscarFocosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarFocosBtnMouseClicked
        // TODO add your handling code here:
        var ip = customTextField2.getText();
        var foquito = (FocoInteligente) ControllerLightbulb.search(ip);
        if (foquito == null) {
            JOptionPane.showMessageDialog(this, "No se tienen registros relacionados a la busqueda","Error",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        customTextField2.setText(foquito.getIp());
        customTextField5.setText(foquito.getNombre());
        customChoose1.setSelectedItem(foquito.getModelo());
        customTextField6.setText(String.valueOf(foquito.getPotenciaDeConsumo()));
        customTextField4.setText(String.valueOf(foquito.getIntensidadMaxima()));
    }//GEN-LAST:event_buscarFocosBtnMouseClicked

    private void eliminarFocosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarFocosBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarFocosBtnMouseClicked

    private void customTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customTextField2KeyTyped
        // TODO add your handling code here:
        String ip=customTextField2.getText();
        if(ip.matches(IPV4_PATTERN_ALLOW_LEADING_ZERO)){
            System.out.println("si");
        }else{
            System.out.println("no");
        }
    }//GEN-LAST:event_customTextField2KeyTyped

    private void eliminarFocosBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarFocosBtnMousePressed
        // TODO add your handling code here:
        try{
            ControllerLightbulb.delete(customTextField2.getText());
            JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente");
            limpiar();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }
    }//GEN-LAST:event_eliminarFocosBtnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLightbulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLightbulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLightbulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLightbulb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateLightbulb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.CustomButton buscarFocosBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private components.CustomChoose customChoose1;
    private components.CustomTextField customTextField2;
    private components.CustomTextField customTextField4;
    private components.CustomTextField customTextField5;
    private components.CustomTextField customTextField6;
    private components.CustomButton editarFocosBtn;
    private components.CustomButton eliminarFocosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private components.CustomButton registrarFocosBtn;
    // End of variables declaration//GEN-END:variables


public void limpiar(){
    customTextField2.setText("");
    customChoose1.setSelectedItem("");
    customTextField5.setText("");
    customTextField6.setText("");
    customTextField4.setText("");
}


}
