/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.ControllerSensor;
import java.awt.event.KeyEvent;
import java.util.UUID;
import javax.swing.JOptionPane;
import models.SensorTemperatura;
import utils.Fonts;
import utils.Colors;

/**
 *
 * @author Usuario
 */
public class CreateSensor extends javax.swing.JFrame {
    private static final String IPV4_PATTERN_ALLOW_LEADING_ZERO =
            "^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
            "([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
            "([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\." +
            "([01]?\\d\\d?|2[0-4]\\d|25[0-5])$";
    public CreateSensor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customTextField2 = new components.CustomTextField();
        customTextField4 = new components.CustomTextField();
        customChoose1 = new components.CustomChoose();
        btnEliminar = new components.CustomButton();
        btnRegistrar = new components.CustomButton();
        btnEditar = new components.CustomButton();
        btnBuscar = new components.CustomButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Colors.white);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(Colors.white);
        jPanel1.setForeground(Colors.white);
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(Fonts.title);
        jLabel1.setForeground(Colors.mediumBlue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Sensor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, -1));

        jLabel2.setFont(Fonts.normal);
        jLabel2.setText("IP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(Fonts.normal);
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setFont(Fonts.normal);
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setFont(Fonts.normal);
        jLabel5.setText("Tipo Sensor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel6.setFont(Fonts.normal);
        jLabel6.setText("Unidades de medida");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        customTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(customTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 680, -1));

        customTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(customTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 680, -1));

        customChoose1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ds18b20", "DHT11", "ARD-360" }));
        jPanel1.add(customChoose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 680, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 130, 40));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 130, 40));

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 130, 40));

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 130, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 670, 60));

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Fahrenheit");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Celcius");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField4ActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        String units = "";
        
        if(jCheckBox1.isSelected()){  units += "F ";  }
        if(jCheckBox2.isSelected()){  units += "C ";  }
        
        String ip = customTextField2.getText();
        if(!ip.matches(IPV4_PATTERN_ALLOW_LEADING_ZERO)){
            JOptionPane.showMessageDialog(this, "Ingrese una IP valida");
            return;
        }
        String nombre = customTextField4.getText();
        String tipo = this.jTextArea1.getText();
        if(ip.equals("") || units.equals("") || nombre.equals("") || tipo.equals("")){
            JOptionPane.showMessageDialog(this, "Ingresa todos los datos, por favor");
            return;
        }
        
        SensorTemperatura sensorTemperatura = new SensorTemperatura(
                "1.2.2.3",
                UUID.randomUUID().toString(),
                ip,
                "apagado",
                nombre,
                this.customChoose1.getSelectedItem().toString(),
                10,
                units,
                0,
                100,
                tipo
        );
        ControllerSensor.add(sensorTemperatura);
        JOptionPane.showMessageDialog(this, "Se ha agregado correctamente");
        clear();
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        String units = "";
        
        if(jCheckBox1.isSelected()){  units += "F ";  }
        if(jCheckBox2.isSelected()){  units += "C ";  }
        
        String ip = customTextField2.getText();
        if(!ip.matches(IPV4_PATTERN_ALLOW_LEADING_ZERO)){
            JOptionPane.showMessageDialog(this, "Ingrese una IP valida");
            return;
        }
        
        String nombre = customTextField4.getText();
        String tipo = this.jTextArea1.getText();
        if(ip.equals("") || units.equals("") || nombre.equals("") || tipo.equals("")){
            JOptionPane.showMessageDialog(this, "Ingresa todos los datos, por favor");
            return;
        }
        
        SensorTemperatura nuevo = new SensorTemperatura(
                "1.2.2.3",
                UUID.randomUUID().toString(),
                ip,
                "apagado",
                nombre,
                this.customChoose1.getSelectedItem().toString(),
                10,
                units,
                0,
                100,
                tipo
        );
        ControllerSensor.edit(ip, nuevo);
        JOptionPane.showMessageDialog(this, "Se ha editado exitosamente");
    }//GEN-LAST:event_btnEditarMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        String ip = customTextField2.getText();
        
        if(!ip.equals("")){
            ControllerSensor.delete(ip);
            JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente");
            clear();
            return;
        }
        JOptionPane.showMessageDialog(this, "No se ha encontrado un Sensor con esa IP");
        clear();
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        
        String ip = customTextField2.getText();
        if(!ip.matches(IPV4_PATTERN_ALLOW_LEADING_ZERO)){
            JOptionPane.showMessageDialog(this, "Ingrese una IP valida");
            return;
        }
        
        if(!ip.equals("")){
                SensorTemperatura sensor = null;
                sensor = (SensorTemperatura) ControllerSensor.search(ip);
                if(null != sensor){
                    customTextField4.setText(sensor.getNombre());
                    jTextArea1.setText(sensor.getTipoSensor());
                    String units = sensor.getUnidades();
                    if(units.equals("F ")){
                        jCheckBox1.setSelected(true);
                    }   
                    if(units.equals("c ")){
                        jCheckBox2.setSelected(true);
                    }
                    return;
                }
              JOptionPane.showMessageDialog(this, "No se ha encontrado un dispositivo con esa IP");
              return;
        } 
        JOptionPane.showMessageDialog(this, "Ingresa una IP para buscar");
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void customTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customTextField2KeyTyped
        char in = evt.getKeyChar();
        if(!(Character.isDigit(in)) && !(in == KeyEvent.VK_BACK_SPACE)  && !(in == KeyEvent.VK_PERIOD)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_customTextField2KeyTyped

    
    private void clear(){
        jTextArea1.setText("");
        buttonGroup1.clearSelection();
        customTextField2.setText("");
        customTextField4.setText("");
        customChoose1.setSelectedIndex(1);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSensor().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.CustomButton btnBuscar;
    private components.CustomButton btnEditar;
    private components.CustomButton btnEliminar;
    private components.CustomButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private components.CustomChoose customChoose1;
    private components.CustomTextField customTextField2;
    private components.CustomTextField customTextField4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
