/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import javax.swing.UIManager;
import models.ListaEnlazada;
import utils.Colors;

/**
 *
 * @author angue
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        UIManager.put("MenuBar.background", Colors.mediumBlue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cAct = new javax.swing.JMenuItem();
        cSens = new javax.swing.JMenuItem();
        CVeh = new javax.swing.JMenuItem();
        cBomb = new javax.swing.JMenuItem();
        cGPS = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mAct = new javax.swing.JMenuItem();
        mSens = new javax.swing.JMenuItem();
        mVeh = new javax.swing.JMenuItem();
        mBomb = new javax.swing.JMenuItem();
        mGPS = new javax.swing.JMenuItem();
        MMap = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/c220.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 610));

        jMenuBar1.setBackground(Colors.mediumBlue);
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(Colors.mediumBlue);
        jMenuBar1.setToolTipText("");
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setOpaque(true);

        jMenu1.setBackground(new java.awt.Color(48, 114, 208));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Crear");
        jMenu1.setOpaque(true);

        cAct.setText("Actuador");
        cAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cActMouseClicked(evt);
            }
        });
        cAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActActionPerformed(evt);
            }
        });
        jMenu1.add(cAct);

        cSens.setText("Sensor");
        cSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSensActionPerformed(evt);
            }
        });
        jMenu1.add(cSens);

        CVeh.setText("Vehiculo");
        CVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVehActionPerformed(evt);
            }
        });
        jMenu1.add(CVeh);

        cBomb.setText("Bombilla");
        cBomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBombActionPerformed(evt);
            }
        });
        jMenu1.add(cBomb);

        cGPS.setText("GPS");
        cGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGPSActionPerformed(evt);
            }
        });
        jMenu1.add(cGPS);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(48, 114, 208));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Mostrar");
        jMenu2.setOpaque(true);

        mAct.setText("Actuadores");
        mAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActActionPerformed(evt);
            }
        });
        jMenu2.add(mAct);

        mSens.setText("Sensores");
        mSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSensActionPerformed(evt);
            }
        });
        jMenu2.add(mSens);

        mVeh.setText("Vehiculos");
        mVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVehActionPerformed(evt);
            }
        });
        jMenu2.add(mVeh);

        mBomb.setText("Bombillas");
        mBomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBombActionPerformed(evt);
            }
        });
        jMenu2.add(mBomb);

        mGPS.setText("GPS");
        mGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGPSActionPerformed(evt);
            }
        });
        jMenu2.add(mGPS);

        MMap.setText("Mapa");
        MMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMapActionPerformed(evt);
            }
        });
        jMenu2.add(MMap);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(Colors.mediumBlue);
        jMenu3.setForeground(Colors.mediumBlue);
        jMenu3.setText("__________________________________________________________________________________________________________________________");
        jMenu3.setOpaque(true);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBombActionPerformed
        this.CreateAndAddInternalFrame(new CreateLightbulb());
    }//GEN-LAST:event_cBombActionPerformed

    private void cActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActActionPerformed
        
        this.CreateAndAddInternalFrame(new CreateActuator());
    }//GEN-LAST:event_cActActionPerformed

    private void cActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cActMouseClicked
    }//GEN-LAST:event_cActMouseClicked

    private void cSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSensActionPerformed
        this.CreateAndAddInternalFrame(new CreateSensor());
    }//GEN-LAST:event_cSensActionPerformed

    private void mActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActActionPerformed
        this.CreateAndAddInternalFrame(new TablasActuadores());
    }//GEN-LAST:event_mActActionPerformed

    private void CVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVehActionPerformed
        this.CreateAndAddInternalFrame(new CreateVehicle());
    }//GEN-LAST:event_CVehActionPerformed

    private void cGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cGPSActionPerformed
        this.CreateAndAddInternalFrame(new CreateDeviceGPS());
    }//GEN-LAST:event_cGPSActionPerformed

    private void mSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSensActionPerformed
        this.CreateAndAddInternalFrame(new TablasSensores());
    }//GEN-LAST:event_mSensActionPerformed

    private void mVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVehActionPerformed
        this.CreateAndAddInternalFrame(new TablasVehiculo());
    }//GEN-LAST:event_mVehActionPerformed

    private void mBombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBombActionPerformed
        this.CreateAndAddInternalFrame(new TablasFocos());
    }//GEN-LAST:event_mBombActionPerformed

    private void mGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGPSActionPerformed
        this.CreateAndAddInternalFrame(new TablasGPS());
    }//GEN-LAST:event_mGPSActionPerformed

    private void MMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMapActionPerformed
        this.CreateAndAddInternalFrame(new Map());
    }//GEN-LAST:event_MMapActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CreateAndAddInternalFrame(new CreateVehicle());
    }                                          

        // TODO add your handling code here://GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.CreateAndAddInternalFrame(new CreateDeviceGPS());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMostrarBombillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostrarBombillasActionPerformed
        // TODO add your handling code here:
        this.CreateAndAddInternalFrame(new TablasFocos());
    }//GEN-LAST:event_jMostrarBombillasActionPerformed

    private void CreateAndAddInternalFrame(JFrame frame)
    {
        var internalFrame = new GeneralJInternalFrame(frame.getContentPane());
        this.jDesktopPane1.add(internalFrame);
        internalFrame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public static ListaEnlazada ListaSensores = new ListaEnlazada();
    public static ListaEnlazada ListaFocos = new ListaEnlazada();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CVeh;
    private javax.swing.JMenuItem MMap;
    private javax.swing.JMenuItem cAct;
    private javax.swing.JMenuItem cBomb;
    private javax.swing.JMenuItem cGPS;
    private javax.swing.JMenuItem cSens;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAct;
    private javax.swing.JMenuItem mBomb;
    private javax.swing.JMenuItem mGPS;
    private javax.swing.JMenuItem mSens;
    private javax.swing.JMenuItem mVeh;
    // End of variables declaration//GEN-END:variables
}
